POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{ "username": "Mandeep", "password": "Pass1234!", "email": "adam@mail.com" }

###

POST http://127.0.0.1:8000/login/ 
Content-Type: application/json

{ "username": "ada", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/test_token/
Content-Type: application/json
Authorization: token b61f22b640f40d7a6fc0b0a48d69aef5b9ca1966

###

POST http://127.0.0.1:8000/upload/
Authorization: token b61f22b640f40d7a6fc0b0a48d69aef5b9ca1966
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"
Sample Video Title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"
Sample Video Description
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="vid.mp4"
Content-Type: video/mp4
< /home/mpatwa98/Downloads/vid.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--
