# Generated by Django 5.0.6 on 2024-05-14 18:07

import VideoStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
