# Generated by Django 5.0.6 on 2024-05-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoStore', '0003_alter_videoproject_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
