# Generated by Django 5.0.6 on 2024-05-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoStore', '0004_alter_videoproject_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='title',
        ),
    ]
