# Generated by Django 5.0.6 on 2024-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoStore', '0005_remove_videoproject_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videoproject',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='youtube'),
        ),
    ]
